# trigger:
#   - master
#   - develop

# variables:
#   ELECTRON_CACHE: '$(Pipeline.Workspace)/.cache/electron'
#   ELECTRON_BUILDER_CACHE: '$(Pipeline.Workspace)/.cache/electronbuilder'
#   NPM_CONFIG_CACHE: $(Pipeline.Workspace)/.npm

# jobs:
# - job: Tests
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#     - template: test-template.yml

# - job: Windows
#   pool:
#     vmImage: 'Windows-latest'
#   steps:
#     - template: build-template.yml
#   # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

# - job: Linux
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#     - template: build-template.yml
#   # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

# - job: MacOS
#   pool:
#     vmImage: 'macOS-latest'
#   steps:
#     - template: build-template.yml
#   # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')