[package]
name = "lazycard"
version.workspace = true
edition.workspace = true

[workspace]
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
sqlite = { path = "crates/sqlite" }
config = { path = "crates/config" }
once_cell = "1.17"

[dependencies]
dioxus = "0.3"
dioxus-desktop = "0.3"
dioxus-router = "0.3"
sqlite = { workspace = true }
config = { workspace = true }
database = { path = "crates/database" }
markdown = { path = "crates/markdown" }
rfd = "0.10"
regex = "1.7"
once_cell = { workspace = true }
