[package]
name = "lazycard"
version.workspace = true
edition.workspace = true

[workspace]
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
database = { path = "crates/database" }

[dependencies]
database = { workspace = true }
