[package]
name = "lazycard"
version.workspace = true
edition.workspace = true

[workspace]
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }

[dependencies]
dioxus = "0.3"
dioxus-desktop = "0.3"
dioxus-router = "0.3"
config = { path = "crates/config" }
database = { path = "crates/database" }
markdown = { path = "crates/markdown" }
serde = { workspace = true }
