[package]
name = "markdown"
version.workspace = true
edition.workspace = true

[dependencies]
pulldown-cmark = { version = "0.9", features = ["simd"] }
syntect = "5.0"
is-url = "1.0"
config = { workspace = true }
